### PR TITLE
Witch Role Implementation

### PR DESCRIPTION
**Pull request by hueyl77**
Hi Chris!

Thanks for the awesome slackwolf bot.  I tested it out among my coworkers today and it worked great.  You sir, are an awesome person.

I saw that you needed help implementing some more roles so I went ahead and implemented the Witch Role.  Here are a few things to consider though:

1. The witch can poison *and* heal on the same night, provided he or she has both potions left (not sure which rules you prefer so I implemented the easier one :))

2. The Day message announcing who was killed combines both the wolves kill and the witch poison kill, so the players dont know who were killed by whom.  Is that okay?

3. If a person was attacked by wolves and then was healed, the Day message will say so.  Is that okay?

4. The night will not end if the Witch is confused and forgets to type "!poison #channel noone" or "!heal #channel noone" if he or she has potions left  (it is not automatic).  The only other way I can see to get around this flow is to set a time limit and ends the night if the witch doesn't make a decision by say 12 hours later...adjustable by setOption

5. I am planning to implement a "!status" command to show the players whose actions the game is waiting on.  So that if the night lags on, they can type "!status" and see a message that says "Waiting on the seer to make his or her decision..."  or "Waiting on the witch to make his or her decision..."

Let me know if there is any questions about the code!  I've tested it a few times through but it could probably use a bit more testing.  Thanks!

### CODE REVIEW

**Comment by AshleyPinner** [comment]
> If a person was attacked by wolves and then was healed, the Day message will say so. Is that okay?

IMO it's more tense if the game just says "There was no deaths in the night!" (assuming no one else died). Much more paranoia and fun.

**Comment by hueyl77** [comment]
@AshleyPinner I like that too.  Will implement it if there are no objections.

**Comment by chrisgillis** [comment]
> The witch can poison and heal on the same night, provided he or she has both potions left (not sure which rules you prefer so I implemented the easier one :))
Perfect

> The Day message announcing who was killed combines both the wolves kill and the witch poison kill, so the players dont know who were killed by whom. Is that okay?
Yeah thats how I would play it

> 
If a person was attacked by wolves and then was healed, the Day message will say so. Is that okay?
I like the above comment from Ashley

> The night will not end if the Witch is confused and forgets to type "!poison #channel noone" or "!heal #channel noone" if he or she has potions left (it is not automatic). The only other way I can see to get around this flow is to set a time limit and ends the night if the witch doesn't make a decision by say 12 hours later...adjustable by setOption
The current design is very much turn based, waiting on each party to make their action. I don't think I would want that to change.

> I am planning to implement a "!status" command to show the players whose actions the game is waiting on. So that if the night lags on, they can type "!status" and see a message that says "Waiting on the seer to make his or her decision..." or "Waiting on the witch to make his or her decision..."
Yes. This. Please. There is usually a lot of confusion in channel about who is waiting on what, so this would be awesome.

Also just keep in mind if you want behavior for some of these things to vary, you can always add new options to the game. See `SetOptionCommand`

**Comment by hueyl77** [comment]
Awesome, thanks for the response Chris.  As I was testing by playing with a few friends and all seems to be working great.  

The only bug I found so far crashes the process when I do a !dead command after the Witch has poisoned someone, so I'm looking into it, not sure if I introduced the bug or not but I want to fix it before merging.

I also still need to implement the change @AshleyPinner  suggested regarding not telling players if someone heal or not. 

Lastly I wanted to wrapup the new !status call.

Don't merge the  pull request yet.  Give me a day or two :)

Thanks!

**Comment by hueyl77** [comment]
Oh, one more thing @chrisgillis .  At times my group doesn't like having the extra roles be *randomly* be in the game or not.  Currently if you set the extra roles of Witch Bodyguard Beholder etc. on, they are not *guaranteed* to be in the game.  But sometimes my group absolutely wants to have a witch in the game.  Would it be okay if I add or modify the setOption command to turn the randomness per role on and off?

E.g.

"!setOption role_witch on norandom" (guarantees there will be a witch in the game)
or
"!setOption role_witch on random" (a witch may or may not be in the game)

"!setOption role_wtich on" will still work as before (witch may or may not be in the game)

**Comment by chrisgillis** [comment]
I like `!setOption role_witch on` to try to guarantee a witch player and `!setOption role_witch random` to add them to the random role pool and `!setOption role_witch off` to ensure the witch is never assigned to a player.

I think `!setOption` could be changed to `!setopt` or `!option` for ease of use.

**Comment by hueyl77** [comment]
good suggestions @chrisgillis I'll get that implemented in a bit.

**Comment by chrisgillis** [comment]
Had any time for this? My group is pretty excited :)

**Comment by hueyl77** [comment]
Hi Chris, sorry for taking so long on this.  Got too busy haven't been able to do much work on it until tonight.  The following tasks are finished:

1. !Die command crashes the app is fixed.  

(Witch poisoning was calling killPlayer in the poison command and in the onNightEnd function.  I shouldn't have been calling killPlayer in the command..)

2. !setOption changed to !option

3. added !status command.  
Typing "!status" in the #werewolf channel will display which action is being waited on if night time.

4. If the witch role is "on", it is now a "required" role.  Other optional roles are still random.

5. Made it just say "There was no deaths in the night!" instead of healed or protected message if no one was killed.

========================

It was a bit complex to change the option to have 3 values ("on", "off", "random") because all the options were booleans.  I put that off for now.  Maybe we can revisit later.

I have tested it as much as I can.  Please let me know if you find any bugs.  If anyone wants to help test I've created a slack team for testing:

https://wearecool.slack.com/

Just leave a comment or email me and I'll invite you!  Thanks!
- Huey

**Comment by hueyl77** [comment]
p.s. If you merge this pull request we can look at the other pull requests that has popped up and get them merged too.  May have lots of conflicts but I'm sure we can figure it out.  Thanks!

**Comment by chrisgillis** [comment]
@hueyl77 merged #32  into master for ya

**Comment by hueyl77** [comment]
thansk @chrisgillis 

I'll pull master back into my witch implementation branch and resolve conflicts and update this PR.  Will let you know once it's done thanks :)

**Comment by hueyl77** [comment]
@chrisgillis @awright022 This PR is ready to be reviewed and merged.  I've fixed all the merge conflicts and tested the new witch role and status command extensively.  Again here is a summary on what was changed:

1. added Witch Role, !poison command and !heal command
2. added !status command
3. changed !setOption to just !option
4. witch role is not random if turned on

**Comment by chrisgillis** [comment]
Played a game with our team and everything seemed to work. Merged :)

**Pull request merged**
