### PR TITLE
Documentation, abstract functions

### PR DESCRIPTION
**Pull request by stevenspasbo**
* Added some documentation
* Updated the Command classes functions to be abstract

### CODE REVIEW

**Comment by chrisgillis** [comment]
Any reason you closed the pull request?

**Comment by stevenspasbo** [comment]
There was an issue with one of the commits, I'll fix it later today and reopen it.

**Comment by chrisgillis** [comment]
👍 Changes look great so far. Any interest in being a maintainer for this project?

**Comment by stevenspasbo** [comment]
Sure

**Pull request merged**
